# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - franz-bendezu
    assignees:
      - franz-bendezu
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval:  "daily"
    open-pull-requests-limit: 10
    reviewers:
      - franz-bendezu
    assignees:
      - franz-bendezu
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
