image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
  TAG_LATEST: latest
  TAG_COMMIT: $CI_COMMIT_SHORT_SHA
  IMAGE_NAME_LATEST: $IMAGE_NAME:$TAG_LATEST
  IMAGE_NAME_TAG: $IMAGE_NAME:$TAG_COMMIT

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin

build:
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
    
    DOCKER_BUILDKIT: 1
    BUILDKIT_INLINE_CACHE: 1
  stage: build
  script:
    - docker pull $IMAGE_NAME_LATEST || true
    - docker build -f Dockerfile.native --cache-from $IMAGE_NAME_LATEST -t $IMAGE_NAME_TAG -t $IMAGE_NAME_LATEST .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_NAME_TAG
    - docker push $IMAGE_NAME_LATEST
  tags:
    - docker
  only:
    - main
    - develop
    - next

deploy:
  stage: deploy
  tags:
    - deployment
  script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh  $SERVER_USER@$SERVER_IP "echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin"
    - ssh  $SERVER_USER@$SERVER_IP "docker pull $IMAGE_NAME_LATEST"
    - ssh  $SERVER_USER@$SERVER_IP "mkdir -p $CI_PROJECT_PATH/deploy"
    - scp  /builds/$CI_PROJECT_PATH/$DOCKER_COMPOSE_FILE_PATH $SERVER_USER@$SERVER_IP:$CI_PROJECT_PATH/$DOCKER_COMPOSE_FILE_PATH
    - scp  $ENV_FILE  $SERVER_USER@$SERVER_IP:$CI_PROJECT_PATH/$ENV_FILE_PATH
    - ssh  $SERVER_USER@$SERVER_IP "docker-compose --env-file $CI_PROJECT_PATH/$ENV_FILE_PATH -p $DOCKER_PROJECT_NAME
      -f $CI_PROJECT_PATH/$DOCKER_COMPOSE_FILE_PATH up  -d"
    - ssh  $SERVER_USER@$SERVER_IP "docker image prune --force"
  only:
    - main
    - develop
    - next
  environment:
    name: $CI_COMMIT_REF_NAME
