spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        metadata_builder_contributor: io.octatec.horext.api.fts.SqlFunctionsMetadataBuilderContributor
server:
  port: 8081
  servlet:
    context-path: /
app:
  firebase-config: ${FIREBASE_JSON}

