version: '3.5'

services:
  horext-api-server:
    image: registry.gitlab.com/horext-app/api-server:latest
    container_name: horext-api-server-dev
    ports:
      - "8080"
    networks:
      - horext-api-network  
      - letsencrypt
networks:
  letsencrypt:
    external:
      name: letsencrypt
  horext-api-network:
    external:
      name: pg-database
