version: '3.8'

services:
  api-server:
    image:  ${IMAGE_NAME}
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      server_servlet_contextPath: /
      FIREBASE_JSON: ${FIREBASE_JSON}
      VIRTUAL_PORT: ${SERVER_PORT}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    ports:
      - ${SERVER_PORT}
    networks:
      - horext-api-network
      - letsencrypt
networks:
  letsencrypt:
    external:
      name: letsencrypt
  horext-api-network:
    external:
      name: pg-database