services:
  api-server:
    image: ${IMAGE_NAME}
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      THREAD_API_URL: ${THREAD_API_URL}
      server_servlet_contextPath: /
      FIREBASE_JSON: ${FIREBASE_JSON}
      VIRTUAL_PORT: ${SERVER_PORT}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # HTTPS router
      - "traefik.http.routers.api-server.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.api-server.entrypoints=websecure"
      - "traefik.http.routers.api-server.tls=true"
      - "traefik.http.routers.api-server.tls.certresolver=le"
      - "traefik.http.routers.api-server.priority=10"
      # HTTP router (for redirect)
      - "traefik.http.routers.api-server-http.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.api-server-http.entrypoints=web"
      - "traefik.http.routers.api-server-http.middlewares=redirect-to-https"
      # Middleware for HTTPS redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Service configuration
      - "traefik.http.services.api-server.loadbalancer.server.port=${SERVER_PORT}"
    ports:
      - ${SERVER_PORT}
    networks:
      - proxy
      - horext-api-network
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/actuator/health"]

networks:
  proxy:
    name: proxy
    external: true
  horext-api-network:
    name: pg-database
    external: true
