version: '3.8'

services:
  api-server:
    image: ${IMAGE_NAME}
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      THREAD_API_URL: ${THREAD_API_URL}
      server_servlet_contextPath: /
      FIREBASE_JSON: ${FIREBASE_JSON}
      VIRTUAL_PORT: ${SERVER_PORT}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    ports:
      - ${SERVER_PORT}
    networks:
      - horext-api-network
      - letsencrypt
    deploy:
      resources:
        limits:
          cpus: '0.50'      # Limit to half a CPU core
          memory: 768M      # Limit to 768MB RAM
        reservations:
          cpus: '0.30'
          memory: 256M
      replicas: 1           # Only one replica per environment
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/actuator/health"]
networks:
  letsencrypt:
    name: letsencrypt
    external: true
  horext-api-network:
    name: pg-database
    external: true
