services:
  api-server:
    image: ${IMAGE_NAME}
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      THREAD_API_URL: ${THREAD_API_URL}
      server_servlet_contextPath: /
      FIREBASE_JSON: ${FIREBASE_JSON}
      VIRTUAL_PORT: ${SERVER_PORT}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    ports:
      - ${SERVER_PORT}
    networks:
      - horext-api-network
      - proxy
    deploy:
      resources:
        limits:
          cpus: "0.50" # Limit to half a CPU core
          memory: 768M # Limit to 768MB RAM
        reservations:
          cpus: "0.30"
          memory: 256M
      replicas: 1 # Only one replica per environment
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-server.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.api-server.entrypoints=websecure"
      - "traefik.http.routers.api-server.tls.certresolver=le"
      - "traefik.http.services.api-server.loadbalancer.server.port=${SERVER_PORT}"
      - "traefik.http.services.api-server.loadbalancer.server.scheme=http"
      - "traefik.http.routers.api-server.middlewares=api-server-redirect@docker"
      - "traefik.http.middlewares.api-server-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.api-server-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.api-server.service=api-server"
      - "traefik.http.services.api-server.loadbalancer.healthcheck.path=/actuator/health"
      - "traefik.http.services.api-server.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.api-server.loadbalancer.healthcheck.timeout=10s"
      - "traefik.http.services.api-server.loadbalancer.healthcheck.retries=3"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/actuator/health"]
networks:
  proxy:
    name: proxy
    external: true
  horext-api-network:
    name: pg-database
    external: true
