version: '3.5'

services:
  horext-api-server:
    image: registry.gitlab.com/horext-app/api-server/dev:latest
    container_name: horext-api-server
    ports:
      - "8080"
    networks:
      - api-network
      - letsencrypt
networks:
  letsencrypt:
    external:
      name: letsencrypt
  api-network:
    external:
      name: pg-database
