insert into course (id, created_at, updated_at, name, code)
values  ('SW101', null, null, 'Introducción a la Ingeniería de Software', null),
        ('TE205', null, null, 'Dibujo y Geometría Descriptiva', null),
        ('SW305', null, null, 'Algoritmia y Estructura de Datos Avanzada', null),
        ('SW301', null, null, 'Arquitectura de Computadoras I', null),
        ('SW303', null, null, 'Lenguajes de Programación I (Imperativo)', null),
        ('SW401', null, null, 'Análisis y Modelamiento de Datos', null),
        ('SW405', null, null, 'Ingeniería de requerimientos I', null),
        ('SW407', null, null, 'Sistemas Operativos', null),
        ('SW403', null, null, 'Lenguaje de Programación II (Orientado a Objetos)', null),
        ('SW501', null, null, 'Arquitectura de Computadoras II', null),
        ('SW503', null, null, 'Análisis y Modelamiento de Comportamiento', null),
        ('SW505', null, null, 'Construcción de software I (fundamentos, practicas)', null),
        ('SW507', null, null, 'Redes y Comunicaciones', null),
        ('HU501', null, null, 'Taller de efectividad personal', null),
        ('SW608', null, null, 'Lenguajes de Dominio Especifico', null),
        ('SW609', null, null, 'Sistemas de Gestión de Base de Datos', null),
        ('SW601', null, null, 'Etica en la Ingeniería de Software', null),
        ('SW603', null, null, 'Diseño de Software', null),
        ('SW605', null, null, 'Ingeniería de requerimientos II', null),
        ('SW701', null, null, 'Gestión del mantenimiento, configuración y cambios del software', null),
        ('SW705', null, null, 'Taller de Ingeniería de Software I', null),
        ('SW707', null, null, 'Construcción de software II (Herramientas y tecnologías)', null),
        ('SW708', null, null, 'Arquitectura de soluciones de software', null),
        ('SW709', null, null, 'Verificación y validación del Software', null),
        ('SW703', null, null, 'Sistemas embebidos y en tiempo real', null),
        ('SW803', null, null, 'Aprendizaje automático I (machine learning I)', null),
        ('SW805', null, null, 'Ingeniería Económica para Software', null),
        ('SW809', null, null, 'Aseguramiento de Calidad del Software', null),
        ('SW807', null, null, 'Procesos de Ingeniería Software', null),
        ('GS804', null, null, 'Administración de empresas de software', null),
        ('HU801', null, null, 'Taller de efectividad profesional', null),
        ('SW901', null, null, 'Aprendizaje automático II (machine learning II)', null),
        ('SW902', null, null, 'Proyecto de Tesis en Ingeniería de Software I', null),
        ('SW903', null, null, 'Taller de Innovación y tecnologías emergentes', null),
        ('SW904', null, null, 'Seguridad en Redes y Desarrollo de Software seguro', null),
        ('SW907', null, null, 'Metodologías Agiles para Proyectos de Software', null),
        ('SW905', null, null, 'Taller de Ingeniería de Software II', null),
        ('SW001', null, null, 'Proyecto de Tesis en Ingeniería de Software II', null),
        ('SW002', null, null, 'Topicos Especiales en Ingeniería de Software', null),
        ('SW003', null, null, 'Gestión de SERVICIOS DEL SOFTWARE', null),
        ('SW004', null, null, 'Gestión de Proyectos de SOFTWARE', null),
        ('SW005', null, null, 'Taller de Emprendimiento en base a soluciones de software', null),
        ('SW111', null, null, 'Transformación digital', null),
        ('SW112', null, null, 'Computación Gráfica', null),
        ('SW113', null, null, 'Cloud computing', null),
        ('SW114', null, null, 'Big Data /Data Science', null),
        ('SW115', null, null, 'Computación Paralela', null),
        ('SW116', null, null, 'Taller de Design Thinking', null),
        ('SW110', null, null, 'Seguridad de la información', null),
        ('SW117', null, null, 'Marketing digital', null),
        ('SW119', null, null, 'Principios de UX /UI', null),
        ('SW120', null, null, 'Desarrollo de aplicaciones móviles', null),
        ('SW121', null, null, 'Desarrollo de aplicaciones web', null),
        ('SW122', null, null, 'Internet de las cosas y nanocosas', null),
        ('SW123', null, null, 'Desarrollo de Videojuegos', null),
        ('SW124', null, null, 'Industria 4.0 (blockchain, impresoras 3d, smart cities…)', null),
        ('SW125', null, null, 'Ciberseguridad y Hackeo etico', null),
        ('SW126', null, null, 'Gestión de Servicios TI', null),
        ('SW127', null, null, 'Modelo del proceso de desarrollo de SW', null),
        ('SW128', null, null, 'Desarrollo de aplicaciones biométricas', null),
        ('SW129', null, null, 'Sistemas georeferenciales', null),
        ('SW130', null, null, 'Taller de desarrollo y operaciones continuas', null),
        ('SW132', null, null, 'Taller de desarrollo seguro', null),
        ('EE525', null, null, 'ANTENAS', null),
        ('HS131', null, null, 'Sociología', null),
        ('AFA531', null, null, 'Lenguaje', null),
        ('EE347', null, null, 'Electrificacion Rural', null),
        ('ST150', null, null, 'ANALITICA DE DATOS', null),
        ('ST605', null, null, 'ARQUITECTURA EMPRESARIAL', null),
        ('ST702', null, null, 'TALLER DE DINAMICA DE SISTEMAS', null),
        ('TE604', null, null, 'MAQUINARIA E INSTRUMENTACION INDUSTRIAL', null),
        ('GP314', null, null, 'Mercadotecnia', null),
        ('AFA611', null, null, 'Dibujo Manual 1', null),
        ('AFA621', null, null, 'Geometria Descriptiva', null),
        ('AFA102', null, null, 'Taller De Diseño 2', null),
        ('AFA406', null, null, 'Estadistica 1', null),
        ('AFA441', null, null, 'Leyes Y Fenomenos Fisicos', null),
        ('AFA492', null, null, 'Taller Invest. En Historia 2', null),
        ('AFA491', null, null, 'Taller Invest. En Historia 1', null),
        ('AFA608', null, null, 'Croquis Arquitectónico', null),
        ('APA402', null, null, 'Critica de la arquitectura contemporánea', null),
        ('APA322', null, null, 'Construcción 2', null),
        ('APA321', null, null, 'Construcción 1', null),
        ('EE152', null, null, 'FUNDAMENTOS DE INGENIERÍA DEL COMPUTADOR', null),
        ('BFI05', null, null, 'FUNDAMENTOS DE INGENIERIA TÉRMICA Y DE FLUIDOS', null),
        ('BMA09', null, null, 'PROGRAMACIÓN ORIENTADA A OBJETOS', null),
        ('BMA10', null, null, 'PROBABILIDADES Y ESTADÍSTICA', null),
        ('FI403', null, null, 'FÍSICA III', null),
        ('MA133', null, null, 'MATEMÁTICAS III', null),
        ('MA611', null, null, 'ESTADÍSTICA Y PROBABILIDADES', null),
        ('BFI09', null, null, 'INTRODUCCIÓN A LA FÍSICA DEL ESTADO SÓLIDO', null),
        ('EE305', null, null, 'ELECTROTECNIA Y CABLEADO DE REDES', null),
        ('EE111', null, null, 'ANÁLISIS DE CIRCUITOS ELÉCTRICOS I', null),
        ('EE340', null, null, 'PRACTICAS DE INTRODUCCION AL DISEÑO ELECTRICO', null),
        ('EE341', null, null, 'INTRODUCCIÓN AL DISEÑO ELÉCTRICO', null),
        ('FI904M', null, null, 'INTRODUCCIÓN A LA FÍSICA DEL ESTADO SÓLIDO', null),
        ('MA143', null, null, 'MATEMÁTICAS IV', null),
        ('CB123', null, null, 'MÉTODOS ESTOCÁSTICOS', null),
        ('AFA511', null, null, 'Bases Y Metodologia Del Trabajo Intelectual', null),
        ('AFA514', null, null, 'Historia De La Cultura', null),
        ('AFA612', null, null, 'Dibujo Manual 2', null),
        ('AFA103', null, null, 'Taller De Diseño 3', null),
        ('EE112', null, null, 'ANÁLISIS DE CIRCUITOS ELÉCTRICOS II', null),
        ('EE131', null, null, 'LABORATORIO DE CIRCUITOS ELÉCTRICOS I', null),
        ('AFA271', null, null, 'Urbanismo 1', null),
        ('AFA381', null, null, 'Arquitectura Bioclimatica 1', null),
        ('AFA346', null, null, 'Materiales Y Procesos 1', null),
        ('AFA396', null, null, 'Modelacion Estructural', null),
        ('AFA516', null, null, 'Arquitectura E Historia 1', null),
        ('AFA613', null, null, 'Dibujo Digital 1', null),
        ('AFA104', null, null, 'Taller De Diseño 4', null),
        ('AFA272', null, null, 'Urbanismo 2', null),
        ('AFA382', null, null, 'Arquitectura Bioclimatica 2', null),
        ('AFA347', null, null, 'Materiales Y Procesos 2', null),
        ('AFA397', null, null, 'Predimensionamiento Estructural', null),
        ('AFA517', null, null, 'Arquitectura E Historia 2', null),
        ('AFA614', null, null, 'Dibujo Digital 2', null),
        ('AFA105', null, null, 'Taller De Diseño 5', null),
        ('EE411', null, null, 'DISPOSITIVOS ELECTRÓNICOS', null),
        ('EM111', null, null, 'TERMODINÁMICA', null),
        ('FI463', null, null, 'TEORÍA DE CAMPOS ELECTROMAGNÉTICOS', null),
        ('HH221', null, null, 'DINÁMICA DE FLUIDOS', null),
        ('MA185', null, null, 'MATEMÁTICAS V', null),
        ('MA195', null, null, 'MÉTODOS NUMÉRICOS', null),
        ('EC119', null, null, 'MECÁNICA DE SÓLIDOS', null),
        ('EE132', null, null, 'LABORATORIO DE CIRCUITOS ELÉCTRICOS II', null),
        ('EE210', null, null, 'MÁQUINAS ELÉCTRICAS', null),
        ('EE363', null, null, 'MEDIDAS ELÉCTRICAS I', null),
        ('EE421', null, null, 'CIRCUITOS ELECTRÓNICOS I (L3)', null),
        ('EE441', null, null, 'LABORATORIO DE ELECTRÓNICA I', null),
        ('EE513', null, null, 'TELECOMUNICACIONES I', null),
        ('EE521', null, null, 'PROPAGACIÓN Y RADIACIÓN ELECTROMAGNÉTICA I', null),
        ('EE635', null, null, 'SISTEMAS DIGITALES I', null),
        ('AFA273', null, null, 'Urbanismo 3', null),
        ('AFA383', null, null, 'Arquitectura Bioclimatica 3', null),
        ('AFA348', null, null, 'Instalaciones', null),
        ('AFA398', null, null, 'Estructuras Especiales', null),
        ('AFA518', null, null, 'Arquitectura E Historia 3', null),
        ('AFA615', null, null, 'Dibujo Digital 3', null),
        ('AFA106', null, null, 'Taller De Diseño 6', null),
        ('AFA161', null, null, 'Gestion 1', null),
        ('AFA543', null, null, 'Arquitectura Peruana 1', null),
        ('AFA107', null, null, 'Taller De Diseño 7', null),
        ('AFA162', null, null, 'Gestion 2', null),
        ('AFA544', null, null, 'Arquitectura Peruana 2', null),
        ('AFA108', null, null, 'Taller De Diseño 8', null),
        ('AFA163', null, null, 'Gestion 3', null),
        ('AFA545', null, null, 'Arquitectura Peruana 3', null),
        ('GP324', null, null, 'Gestion Logistica Y De Operaciones', null),
        ('GP535', null, null, 'Proyecto De Tesis En Ing. Industrial I', null),
        ('ST205', null, null, 'Topicos De Ingenieria De Sistemas', null),
        ('ST295', null, null, 'Ingenieria Empresarial', null),
        ('ST203', null, null, 'Modelamiento De Datos', null),
        ('HS161', null, null, 'Protocolo', null),
        ('HS144', null, null, 'Comportamiento Organizacional', null),
        ('TP113', null, null, 'Sistemas Electricos Y Electronicos', null),
        ('HS302', null, null, 'Idiomas Ii', null),
        ('HS204', null, null, 'Legislacion Empresarial', null),
        ('TP254', null, null, 'Automatizacion Y Control De Procesos', null),
        ('ST255', null, null, 'Gestion De Proyectos Informaticos', null),
        ('ST254', null, null, 'Administracion De La Calidad De Software', null),
        ('TP414', null, null, 'Introduccion A La Ingenieria Ambiental', null),
        ('CB143', null, null, 'Matematica Aplicada', null),
        ('ST222', null, null, 'Lenguajes De Programacion', null),
        ('APA323', null, null, 'Gestión De Obras', null),
        ('APA324', null, null, 'Diseño De Acabados', null),
        ('APA121', null, null, 'Gestión De Proyectos', null),
        ('APA713', null, null, 'Dibujo De Arte', null),
        ('APA226', null, null, 'Introducción A La Gestión Del Riesgo', null),
        ('APA227', null, null, 'Sistemas De Información Geográfica', null),
        ('APA228', null, null, 'Legislación Urbana', null),
        ('APA222', null, null, 'Desarrollo De Áreas Urbanas', null),
        ('APA718', null, null, 'Telares', null),
        ('GE120', null, null, 'Modelos Probabilisticos y Analisis de Riesgos', null),
        ('GP805', null, null, 'Mercadotecia', null),
        ('APA411', null, null, 'Historia de la arquitectura 1', null),
        ('APA332', null, null, 'Estructura 2', null),
        ('APA613', null, null, 'Dibujo y diseño digital', null),
        ('APA612', null, null, 'Dibujo arquitectónico 2', null),
        ('EE610', null, null, 'ANÁLISIS DE SEÑALES Y DE SISTEMAS', null),
        ('IP101', null, null, 'INGLÉS PROFESIONAL I', null),
        ('IT313', null, null, 'LAB. DE INSTRUMENTOS DE TELECOMUNICACIONES', null),
        ('IT433', null, null, 'CONTROL AUTOMÁTICO', null),
        ('EE240', null, null, 'LABORATORIO DE MÁQUINAS ELÉCTRICAS', null),
        ('EE241', null, null, 'LABORATORIO DE MÁQUINAS ELÉCTRICAS I', null),
        ('EE364', null, null, 'MEDIDAS ELÉCTRICAS II', null),
        ('EE391', null, null, 'LABORATORIO DE MEDIDAS ELÉCTRICAS I', null),
        ('EE422', null, null, 'CIRCUITOS ELECTRÓNICOS II', null),
        ('EE442', null, null, 'LABORATORIO DE ELECTRÓNICA II', null),
        ('EE523', null, null, 'LÍNEAS DE TRANSMISIÓN', null),
        ('EE524', null, null, 'PROPAGACIÓN Y RADIACIÓN ELECTROMAGNÉTICA II', null),
        ('EE612', null, null, 'PROCESAMIENTO DIGITAL DE SEÑALES', null),
        ('EE636', null, null, 'SISTEMAS DIGITALES II', null),
        ('IT114', null, null, 'CIRCUITOS ELÉCTRONICOS DIGITALES', null),
        ('IT134', null, null, 'MICROPROCESADORES', null),
        ('IT144', null, null, 'LABORATORIO DE CIRCUITOS ANALÓGICOS', null),
        ('IT213', null, null, 'LÍNEAS DE TRANSMISIÓN', null),
        ('IT414', null, null, 'CONTROL TEMPORAL', null),
        ('IT514', null, null, 'TELECOMUNICACIONES II', null),
        ('IT563', null, null, 'LABORATORIO DE TELECOMUNICACIONES I', null),
        ('EE242', null, null, 'LABORATORIO DE MÁQUINAS ELÉCTRICAS II', null),
        ('EE392', null, null, 'LABORATORIO DE MEDIDAS ELÉCTRICAS II', null),
        ('EE423', null, null, 'CIRCUITOS ELECTRÓNICOS III', null),
        ('EE425', null, null, 'MICROELECTRÓNICA', null),
        ('EE443', null, null, 'LABORATORIO DE ELECTRÓNICA III', null),
        ('EE432', null, null, 'CIRCUITOS ELECTRÓNICOS II P', null),
        ('EE514', null, null, 'TELECOMUNICACIONES II', null),
        ('EE616', null, null, 'CONTROL II', null),
        ('EM121', null, null, 'MÁQUINAS TÉRMICAS', null),
        ('EM221', null, null, 'TURBOMÁQUINAS', null),
        ('IT145', null, null, 'LABORATORIO DE CIRCUITOS DIGITALES', null),
        ('IT214', null, null, 'FILTROS DIGITALES', null),
        ('IT215', null, null, 'CIRCUITOS DE TELECOMUNICACIÓN', null),
        ('IT224', null, null, 'MICROONDAS', null),
        ('IT243', null, null, 'RADIOPROPAGACIÓN', null),
        ('IT515', null, null, 'TELECOMUNICACIONES III', null),
        ('IT524', null, null, 'REDES TELEMÁTICAS', null),
        ('IT557', null, null, 'TÓPICOS ESPECIALES', null),
        ('IT564', null, null, 'LABORATORIO DE TELECOMUNICACIONES II', null),
        ('CI105', null, null, 'FORMULACIÓN Y PROYECTOS DE INVERSIÓN', null),
        ('CI106', null, null, 'GESTIÓN DE PROYECTOS', null),
        ('EE235', null, null, 'DISEÑO DE MÁQUINAS ELÉCTRICAS I', null),
        ('EE243', null, null, 'LABORATORIO DE MÁQUINAS ELÉCTRICAS III', null),
        ('EE389', null, null, 'ECONOMÍA DE LA ENERGÍA', null),
        ('EE435', null, null, 'ELECTRÓNICA INDUSTRIAL', null),
        ('EE515', null, null, 'TELECOMUNICACIONES III', null),
        ('EE526', null, null, 'RADIOPROPAGACIÓN', null),
        ('EE535', null, null, 'SISTEMAS DE RADIODIFUSIÓN', null),
        ('EE545', null, null, 'MICROONDAS', null),
        ('EE625', null, null, 'CONTROL III', null),
        ('EE641', null, null, 'LABORATORIO DE CONTROL', null),
        ('IT235', null, null, 'SISTEMAS DE MICROONDAS', null),
        ('IT255', null, null, 'FIBRAS ÓPTICAS', null),
        ('IT264', null, null, 'LABORATORIO DE CIRCUITOS DE TELECOMUNICACIONES', null),
        ('IT525', null, null, 'PROTOCOLO DE COMUNICACIÓN', null),
        ('IT535', null, null, 'CONMUTACIÓN TELEFÓNICA', null),
        ('IT565', null, null, 'LABORATORIO DE TELECOMUNICACIONES III', null),
        ('AHD93', null, null, 'LEGISLACIÓN INDUSTRIAL, LABORAL Y TRIBUTARIA', null),
        ('CB525', null, null, 'INGENIERÍA ECONÓMICA', null),
        ('EE387', null, null, 'PLANEAMIENTO  DE PROYECTOS DE ING. ELÉCTRICA', null),
        ('EE388', null, null, 'DISEÑO DE ESTAC.TRANSF.DE MEDIA Y ALTA TENSIÓN', null),
        ('APA223', null, null, 'Arquitectura Del Paisaje', null),
        ('APA224', null, null, 'Movilidad Urbana', null),
        ('APA225', null, null, 'Desarrollo Sostenible', null),
        ('APA601', null, null, 'Geometría Descriptiva', null),
        ('APA343', null, null, 'Vivienda Experimental', null),
        ('APA301', null, null, 'Geología, Geodesia Y Topografía', null),
        ('APA333', null, null, 'Diseño De Instalaciones', null),
        ('APA334', null, null, 'Diseño De Estructuras Especiales', null),
        ('APA335', null, null, 'Metrados Y Presupuestos Del Proyecto', null),
        ('APA341', null, null, 'Acústica', null),
        ('APA413', null, null, 'Historia De La Arquitectura 3', null),
        ('APA501', null, null, 'Estadística', null),
        ('APA422', null, null, 'Taller Restauración De Monumentos', null),
        ('APA401', null, null, 'Teoria De La Arquitectura', null),
        ('APA412', null, null, 'Historia De La Arquitectura 2', null),
        ('APA414', null, null, 'Conservación Del Patrimonio Monumental', null),
        ('APA314', null, null, 'Diseño Bioclimático 3', null),
        ('APA716', null, null, 'Fotografía Y Audiovisuales', null),
        ('APA611', null, null, 'Dibujo Arquitectónico 1', null),
        ('APA345', null, null, 'Critica de la arquitectura contemporánea', null),
        ('APA705', null, null, 'Metodología de la investigación científica', null),
        ('APA105', null, null, 'Diseño arquitectónico 3', null),
        ('APA106', null, null, 'Diseño Arquitectónico 4', null),
        ('APA312', null, null, 'Diseño bioclimático 1', null),
        ('APA313', null, null, 'Diseño bioclimático 2', null),
        ('APA202', null, null, 'Sociología urbana', null),
        ('EE536', null, null, 'SISTEMAS DE TELEVISIÓN', null),
        ('EE546', null, null, 'SISTEMAS DE MICROONDAS', null),
        ('IT246', null, null, 'COMUNICACIONES INALÁMBRICAS', null),
        ('IT265', null, null, 'LABORATORIO DE COMUNICACIONES ÓPTICAS', null),
        ('IT536', null, null, 'IP MULTIMEDIA SUBSYSTEM', null),
        ('IT556', null, null, 'PLANIFICACIÓN DE REDES', null),
        ('IT566', null, null, 'LABORATORIO DE TELECOMUNICACIONES IV', null),
        ('IT616', null, null, 'RADIODIFUSIÓN SONORA', null),
        ('IT626', null, null, 'SISTEMA DE TELEVISIÓN', null),
        ('IT644', null, null, 'TELEVISIÓN DIGITAL', null),
        ('IT716', null, null, 'RADARES', null),
        ('APA614', null, null, 'Diseño Paramétrico', null),
        ('APA331', null, null, 'Estructura 1', null),
        ('APA311', null, null, 'Bases Tecnológicas', null),
        ('APA344', null, null, 'Tecnología Del Bambú', null),
        ('APA346', null, null, 'Tecnología De La Madera', null),
        ('APA721', null, null, 'Escultura Arquitectónica', null),
        ('APA722', null, null, 'Historia Del Arte 1', null),
        ('APA723', null, null, 'Historia Del Arte 2', null),
        ('APA424', null, null, 'Taller De Centros Históricos', null),
        ('APA425', null, null, 'Arquitectura Latinoamericana', null),
        ('APA802', null, null, 'Taller De Investigación 2', null),
        ('APA421', null, null, 'Seminario De Historia De La Arq.', null),
        ('APA342', null, null, 'Iluminación Artificial', null),
        ('APA423', null, null, 'Seminario Ciudad De Lima', null),
        ('APA511', null, null, 'Estadística Para La Investigación', null),
        ('APA801', null, null, 'Taller De Investigación 1', null),
        ('APA134', null, null, 'Gestión De Proyectos Arquitectónicos', null),
        ('APA622', null, null, 'Presentación De Proyectos', null),
        ('APA623', null, null, 'Croquis Arquitectónico', null),
        ('APA702', null, null, 'Comunicación', null),
        ('APA624', null, null, 'Sistemas Gráficos Digitales', null),
        ('APA621', null, null, 'Expresión Digital', null),
        ('APA704', null, null, 'Arteyarquitectura2', null),
        ('APA701', null, null, 'Cultura Contemporánea', null),
        ('GP255', null, null, 'Economia de la Tecnologia', null),
        ('APA712', null, null, 'Teoria Del Color', null),
        ('APA703', null, null, 'Arte Y Arquitectura 1', null),
        ('APA131', null, null, 'Diseño Industrial Para Arquitectos', null),
        ('APA132', null, null, 'Diseño De Interiores', null),
        ('APA133', null, null, 'Teoria Del Diseño', null),
        ('APA201', null, null, 'Geografía Territorial', null),
        ('APA719', null, null, 'Pintura', null),
        ('APA714', null, null, 'Diseño De Mueble', null),
        ('APA715', null, null, 'Cerámica Experimental', null),
        ('APA109', null, null, 'Diseño Arquitectónico 7', null),
        ('APA717', null, null, 'Cine Y Literatura', null),
        ('APA711', null, null, 'Taller De Redacción Académica Y De Investigación', null),
        ('APA107', null, null, 'Diseño Arquitectónico 5', null),
        ('APA108', null, null, 'Diseño Arquitectónico 6', null),
        ('APA101', null, null, 'Creatividad 1', null),
        ('XP200', null, null, 'Practicas Pre-Profesionales Ii', null),
        ('TE603', null, null, 'Control Estadístico De Procesos', null),
        ('MC851', null, null, 'Análisis de Fallas y Peritajes Técnicos', null),
        ('ST275', null, null, 'Auditoria De Sistemas', null),
        ('MC142', null, null, 'Corrosion Y Tecnicas De Proteccion', null),
        ('TP314', null, null, 'Ingenieria Del Producto', null),
        ('AFA109', null, null, 'Taller De Diseño 9', null),
        ('APA104', null, null, 'Diseño arquitectónico 2', null),
        ('APA212', null, null, 'Diseño Urbano 2', null),
        ('APA211', null, null, 'Diseño urbano 1', null),
        ('APA102', null, null, 'Creatividad 2', null),
        ('APA103', null, null, 'Diseño Arquitectónico 1', null),
        ('APA110', null, null, 'Diseño Arquitectónico 8', null),
        ('APA215', null, null, 'Gestión De Proyectos Urbanos', null),
        ('APA213', null, null, 'Diseño Urbano 3', null),
        ('APA214', null, null, 'Diseño Urbano 4', null),
        ('ST339', null, null, 'Comercio Electronico', null),
        ('TP261', null, null, 'IntroducciOn a la Robatica', null),
        ('ST214', null, null, 'Administracion De Base De Datos', null),
        ('ST213', null, null, 'Analisis Y Diseno De Sistemas', null),
        ('TP103', null, null, 'Electricidad Y Electronica Industrial', null),
        ('BFI02', null, null, 'Electromagnetismo Y Optica', null),
        ('TP213', null, null, 'Fisicoquimica Y Operaciones Unitarias', null),
        ('TP123', null, null, 'Sistemas Digitales', null),
        ('ST265', null, null, 'Administracion Del Conocimiento', null),
        ('ST314', null, null, 'Arquitectura Del Computador', null),
        ('EE250', null, null, 'Dibujo Tecnico', null),
        ('GP205', null, null, 'Gestion De Mantenimiento', null),
        ('HS102', null, null, 'Ideologias Contemporaneas', null),
        ('GP202', null, null, 'Microeconomia', null),
        ('HS151', null, null, 'Literatura', null),
        ('BRC01', null, null, 'Redacción Y Comunicación', null),
        ('AFA113', null, null, 'Expresion Visual.', null),
        ('AFA115', null, null, 'Taller De Diseño Arquitectonico Experimental – Poly Port', null),
        ('AFA121', null, null, 'Tipologia Arquitectonica', null),
        ('AFA223', null, null, 'Desarrollo De Areas Urbanas', null),
        ('AFA224', null, null, 'Arquitectura Del Paisaje', null),
        ('AFA232', null, null, 'Diseño Vial Y Problemática Del Transporte', null),
        ('AFA282', null, null, 'Gestion Del Desarrollo Urbano', null),
        ('AFA283', null, null, 'Sociologia Urbana', null),
        ('AFA284', null, null, 'Desarrollo Urbano Sostenible', null),
        ('AFA285', null, null, 'Economia Urbana', null),
        ('AFA314', null, null, 'Acustica', null),
        ('AFA315', null, null, 'Iluminacion', null),
        ('AFA327', null, null, 'Seminario De Acabados', null),
        ('AFA371', null, null, 'Tecnologia De Vivienda De Bajo Costo', null),
        ('AFA372', null, null, 'Tecnologia Del Bambu', null),
        ('AFA373', null, null, 'Tecnologia Del Acero', null),
        ('CB313', null, null, 'Fisica Moderna', null),
        ('BAE01', null, null, 'Actividades Extracurriculares', null),
        ('BEF01', null, null, 'Ética Y Filosofía Política', null),
        ('MC101', null, null, 'Ingeniería Gráfica I', null),
        ('BFI01', null, null, 'Física 1', null),
        ('MB700', null, null, 'Introducción a la Ingeniería Mecánica', null),
        ('MC102', null, null, 'Ingeniería Gráfica II', null),
        ('MC401', null, null, 'Elementos de Máquinas', null),
        ('MS114', null, null, 'Emprendimiento y Liderazgo', null),
        ('MC103', null, null, 'Ingeniería Gráfica III', null),
        ('MC117', null, null, 'Ciencia de los materiales I', null),
        ('MC337', null, null, 'Estática', null),
        ('MB301', null, null, 'Cálculo vectorial', null),
        ('MB613', null, null, 'Estadística Y Probabilidades', null),
        ('MC215', null, null, 'Procesos de Manufactura I', null),
        ('MC118', null, null, 'Ciencia de los Materiales II', null),
        ('BFI03', null, null, 'Física III', null),
        ('MC338', null, null, 'Dinámica', null),
        ('MB157', null, null, 'Ecuaciones Diferenciales', null),
        ('MC216', null, null, 'Procesos de Manufactura II', null),
        ('MC326', null, null, 'Resistencia de Materiales I', null),
        ('MN216', null, null, 'Mecánica de Fluidos I', null),
        ('MN115', null, null, 'Termodinámica I', null),
        ('ML140', null, null, 'Circuitos Eléctricos', null),
        ('MB540', null, null, 'Métodos Numéricos para Ingeniería', null),
        ('MC417', null, null, 'Mecánica de Máquinas', null),
        ('MC328', null, null, 'Resistencia de Materiales II', null),
        ('MN217', null, null, 'Mecánica de Fluidos II', null),
        ('MN116', null, null, 'Termodinámica II', null),
        ('ML203', null, null, 'Electrónica Básica Industrial', null),
        ('MS800', null, null, 'Creatividad e Innovación', null),
        ('MC585', null, null, 'Cálculo de Elementos de Máquinas I', null),
        ('MC610', null, null, 'Cálculo por Elementos y Volúmenes Finitos', null),
        ('MN232', null, null, 'Turbomáquinas I', null),
        ('MT227', null, null, 'Control Automático Clásico y Moderno', null),
        ('ML202', null, null, 'Máquinas Eléctricas', null),
        ('AFA732', null, null, 'Pintura 2', null),
        ('MS407', null, null, 'Ingeniería Económica y Finanzas', null),
        ('MS801', null, null, 'Gestión y Dirección de Proyectos', null),
        ('MC586', null, null, 'Cálculo de Elementos de Máquinas II', null),
        ('MC236', null, null, 'Tecnología de la Soldadura I', null),
        ('SI113', null, null, 'Sistemas de información Gerencial', null),
        ('TE125', null, null, 'Lean Manufacturing', null),
        ('GE126', null, null, 'Ingeniería del Servicio', null),
        ('GE123', null, null, 'Planeamiento y Gestión de Negocios', null),
        ('TE124', null, null, 'Gestión de la Energía', null),
        ('SI124', null, null, 'Comercio Electrónico', null),
        ('SI125', null, null, 'Dinámica de Sistemas Industriales', null),
        ('GE124', null, null, 'Comercio Internacional', null),
        ('GE122', null, null, 'Sistema de Costos', null),
        ('GE121', null, null, 'Diseño y Disposición de Plantas', null),
        ('TE127', null, null, 'Robótica Industrial', null),
        ('TE121', null, null, 'Ergonomia', null),
        ('HU111', null, null, 'Legislación Empresarial y Tributaria', null),
        ('MN139', null, null, 'Motores de Combustión Interna', null),
        ('BMA06', null, null, 'Calculo Avanzado II', null),
        ('AFA512', null, null, 'Metodologia Del Autoaprendizaje', null),
        ('EE385', null, null, 'Valuacion Y Tarificacion De La Energia Electrica', null),
        ('EE752', null, null, 'Topicos Especiales En Electricidad', null),
        ('EE365', null, null, 'Medidas Electricas', null),
        ('EE378', null, null, 'Optimizacion En Sistemas Electricos De Potencia', null),
        ('EE820', null, null, 'Proyectos De Inversion', null),
        ('EE316', null, null, 'Centrales Electricas Ii', null),
        ('EE344', null, null, 'Ingenieria De Iluminacion', null),
        ('EE386', null, null, 'Evaluacion De Proyectos De Ingenieria Electrica', null),
        ('EE317', null, null, 'Gestion De Sistemas Electricos', null),
        ('EE318', null, null, 'Introduccion A Redes Inteligentes Y Microredes', null),
        ('EE410', null, null, 'Analisis De Señales Y Sistemas', null),
        ('EE420', null, null, 'Circuitos Electricos Ii', null),
        ('EE461', null, null, 'Circuitos Electronicos I', null),
        ('EE430', null, null, 'Sistemas Digitales', null),
        ('EE520', null, null, 'Teoria De Campos Electromagneticos', null),
        ('EE621', null, null, 'Controles Electricos Y Automatizacion', null),
        ('EE581', null, null, 'Introduccion Al Diseño Electrico', null),
        ('EE532', null, null, 'Termodinamica Y Turbomaquinas', null),
        ('BMA08', null, null, 'Metodos Numericos', null),
        ('EE325', null, null, 'Lineas De Transmision De Potencia', null),
        ('AFA515', null, null, 'Metodlogia De Investigacion', null),
        ('AFA551', null, null, 'Restauracion De Monumentos', null),
        ('AFA526', null, null, 'Seminario Ciudad De Limia', null),
        ('MN317', null, null, 'Transferencia de Calor y Masa', null),
        ('MT207', null, null, 'Electricidad y Automatización Industrial (+L)', null),
        ('MS404', null, null, 'Metodología de la Investigación', null),
        ('MS725', null, null, 'Gestión de Operaciones', null),
        ('MC801', null, null, 'Proyecto de Ingeniería I', null),
        ('MC850', null, null, 'Ingeniería Automotriz en Maquinaria Pesada', null),
        ('ML845', null, null, 'Ingeniería de Energías Renovables', null),
        ('MN165', null, null, 'Centrales Termoeléctricas', null),
        ('MC655', null, null, 'Ingeniería de Mantenimiento y Confiabilidad', null),
        ('MS803', null, null, 'Sistemas de Gestión Ambiental', null),
        ('MC802', null, null, 'Proyectos de Ingeniería II', null),
        ('MN374', null, null, 'Refrigeración y Aire Acondicionado', null),
        ('ML715', null, null, 'Centrales Hidroeléctricas', null),
        ('AFA101', null, null, 'Taller De Diseño I', null),
        ('AFA361', null, null, 'Geodesia Y Topografia', null),
        ('AFA431', null, null, 'Vectores Y Matrices', null),
        ('HS141', null, null, 'Filosofía y Etica', null),
        ('SI805', null, null, 'Integración de Sistemas', null),
        ('TE701', null, null, 'Análisis de Procesos de Manufactura', null),
        ('TE901', null, null, 'Seguridad y Salud Ocupacional', null),
        ('SI904', null, null, 'Seguridad de Sistemas', null),
        ('SI903', null, null, 'Implementacion de Sistemas', null),
        ('SI902', null, null, 'Ingenieria de Sistemas de Servicio', null),
        ('SI901', null, null, 'Proyecto de Tesis en Ing. Sistemas I', null),
        ('SI203', null, null, 'Teoría y Ciencia de Sistemas', null),
        ('CB222', null, null, 'Química Industrial II', null),
        ('SI201', null, null, 'Psicología Sistémica', null),
        ('TP302', null, null, 'Diseño Asistido por Computadora', null),
        ('SI602', null, null, 'Dinámica de Sistemas', null),
        ('HU102', null, null, 'Desarrollo Personal', null),
        ('CB221', null, null, 'Quimica Industrial I', null),
        ('SI075', null, null, 'Auditoria de Sistemas', null),
        ('SI605', null, null, 'Arquitectura Empresarial', null),
        ('SI604', null, null, 'Análisis y Diseño de Sistemas', null),
        ('TE502', null, null, 'Resistencia de Materiales', null),
        ('GE502', null, null, 'Ingeniería del Trabajo I', null),
        ('TE601', null, null, 'Ingeniería de Materiales', null),
        ('GE002', null, null, 'Finanzas', null),
        ('GE803', null, null, 'Sistemas Analiticos', null),
        ('GE802', null, null, 'Gestión de la Cadena de Suministro', null),
        ('GE605', null, null, 'Sistema y Gestión Financiera', null),
        ('BIC01', null, null, 'Introducción a la Computación', null),
        ('CB132', null, null, 'Cálculo Multivariable', null),
        ('GE805', null, null, 'Mercadotecnia', null),
        ('HS121', null, null, 'Metodología de la Investigación Científica', null),
        ('GE902', null, null, 'Diseño y Evaluación de Proyectos', null),
        ('HS201', null, null, 'Constitución y Derechos Humanos', null),
        ('SI702', null, null, 'Taller de Dinámica de Sistemas', null),
        ('SI055', null, null, 'Gestión de Proyectos', null),
        ('HS111', null, null, 'Técnicas de comunicación', null),
        ('GE704', null, null, 'Contabilidad de Costos y Presupuestos', null),
        ('GP514', null, null, 'Comercio Internacional', null),
        ('BCR01', null, null, 'Redaccion Y Comunicacion', null),
        ('GP525', null, null, 'Diseno Y Evaluacion De Proyectos', null),
        ('GP585', null, null, 'Topicos De Ingenieria Industrial', null),
        ('HS303', null, null, 'Idiomas Iii', null),
        ('GP203', null, null, 'Macroeconomia', null),
        ('ST204', null, null, 'Taller De Ingenieria De Software I', null),
        ('MC563', null, null, 'Estructuras Metalicas', null),
        ('HS402', null, null, 'Deporte', null),
        ('TP244', null, null, 'Analisis De Manufactura', null),
        ('HS405', null, null, 'Topicos De Negociacion', null),
        ('ST244', null, null, 'Taller De Ingenieria De Software Ii', null),
        ('TP404', null, null, 'Higiene Y Seguridad Industrial', null),
        ('ST414', null, null, 'Inteligencia Artificial', null),
        ('ST243', null, null, 'Taller De Herramientas Realidad Virtual', null),
        ('ST245', null, null, 'Ingenieria De Software Avanzado', null),
        ('MC235', null, null, 'Tecnologia De La Soldadura Ii', null),
        ('MN234', null, null, 'Turbomaquinas Ii', null),
        ('GP235', null, null, 'Gestion Financiera', null),
        ('GP245', null, null, 'Financiamiento Corporativo', null),
        ('MN143', null, null, 'Turbinas A Vapor Y Gas', null),
        ('ST415', null, null, 'Inteligencia Artificial Avanzada', null),
        ('GP304', null, null, 'Logistica Empresarial', null),
        ('ST305', null, null, 'Servicios De Comunicacion De Datos', null),
        ('MC571', null, null, 'Vibraciones Mecanicas', null),
        ('MN515', null, null, 'Energetica', null),
        ('ML839', null, null, 'Electronica De Potencia', null),
        ('MT205', null, null, 'Sistemas Hidroneumaticos', null),
        ('MT634', null, null, 'Analisis De Vibraciones Y De Ruido', null),
        ('GP123', null, null, 'Administracion Y Organizacion', null),
        ('MS614', null, null, 'Medio Ambiente Y Sostenibilidad', null),
        ('MN333', null, null, 'Aparatos Termicos', null),
        ('GP122', null, null, 'Creatividad Empresarial', null),
        ('MN253', null, null, 'Ventilacion Industrial', null),
        ('BMA02', null, null, 'Calculo Integral', null),
        ('MT253', null, null, 'Autotronica', null),
        ('MC432', null, null, 'Seguridad Industrial Y Gestion De Riesgos', null),
        ('MS503', null, null, 'Manufactura Esbelta Y Seis Sigma', null),
        ('MS223', null, null, 'Costos Y Presupuestos', null),
        ('MS527', null, null, 'Gestion Integral De La Calidad', null),
        ('MC426', null, null, 'Mantenimiento De Instalaciones De Petroleo Y Gas Natural', null),
        ('MC429', null, null, 'Mantenimiento De Equipos Y Maquinaria Minera', null),
        ('AFA110', null, null, 'Taller De Diseño 10', null),
        ('AFA131', null, null, 'Seminario De Teoria Y Diseño', null),
        ('AFA215', null, null, 'Seminario De Urbanismo', null),
        ('AFA325', null, null, 'Seminario De Construccion', null),
        ('AFA525', null, null, 'Seminario De Historia Arquitectura', null),
        ('AFA191', null, null, 'Taller Invest. En Arquitectura 1', null),
        ('AFA192', null, null, 'Taller Invest. En Arquitectura 2', null),
        ('AFA293', null, null, 'Taller Invest. En Urbanismo 1', null),
        ('AFA294', null, null, 'Taller Invest. En Urbanismo 2', null),
        ('AFA391', null, null, 'Taller Invest. En Tecnologia 1', null),
        ('AFA392', null, null, 'Taller Invest. En Tecnologia 2', null),
        ('AFA591', null, null, 'Taller Invest. En Historia 1', null),
        ('AFA592', null, null, 'Taller Invest. En Historia 2', null),
        ('AFA384', null, null, 'Equilibrio Termico De Edificacion', null),
        ('AFA374', null, null, 'Tecnologia De La Madera', null),
        ('GE001', null, null, 'Proyecto de Tesis en Ingeniería Industrial II', null),
        ('GE904', null, null, 'Proyecto de Tesis en Ingeniería Industrial I', null),
        ('GE903', null, null, 'Gestión del Talento Humano', null),
        ('GE901', null, null, 'Innovación y Emprendimiento de Negocios', null),
        ('GP565', null, null, 'Gestión de Negocios II', null),
        ('GE905', null, null, 'Planeamiento y Control de Operaciones', null),
        ('GE801', null, null, 'Planeamiento y Gestión Estratégica', null),
        ('SI607', null, null, 'Arquitectura Computacional y Redes', null),
        ('SI601', null, null, 'Investigación de Operaciones II', null),
        ('SI603', null, null, 'Modelado de Procesos de Ciclo de Vida de Sistemas', null),
        ('TE101', null, null, 'Dibujo de Ingeniería', null),
        ('CB501', null, null, 'Dibujo en Ingeniería', null),
        ('GE604', null, null, 'Administración y Organización', null),
        ('GP132', null, null, 'Creatividad Empresarial', null),
        ('CB142', null, null, 'Ecuaciones Diferenciales', null),
        ('SI501', null, null, 'Investigación de Operaciones I', null),
        ('HS101', null, null, 'Desarrollo personal', null),
        ('GE703', null, null, 'Sistemas Integrados Empresariales', null),
        ('CB111', null, null, 'Algebra Lineal', null),
        ('GE101', null, null, 'Introducción a Ingeniería Industrial', null),
        ('SI403', null, null, 'Metodología de los Sistemas Blandos', null),
        ('GE702', null, null, 'Ingeniería Económica', null),
        ('SI035', null, null, 'Proyecto de Tesis en Ing. Sistemas II', null),
        ('GE709', null, null, 'Sistemas de Calidad', null),
        ('GE501', null, null, 'Teoria Organizacional', null),
        ('CB131', null, null, 'Cálculo Integral', null),
        ('TE503', null, null, 'Procesos Industriales I', null),
        ('TE501', null, null, 'Electricidad y Electrónica Industrial', null),
        ('FB305', null, null, 'Estadística y Probabilidades', null),
        ('FB402', null, null, 'Cálculo Numérico', null),
        ('TE301', null, null, 'Físico Química y Operaciones Unitarias', null),
        ('CB402', null, null, 'Estadítica y Probabilidades', null),
        ('SI701', null, null, 'Modelado Sistémico y Simulación', null),
        ('TE302', null, null, 'Diseño Asistido por Computador', null),
        ('GE701', null, null, 'Logística Empresarial', null),
        ('TE602', null, null, 'Procesos Industriales II', null),
        ('FB401', null, null, 'Física II', null),
        ('CB312', null, null, 'Física II', null),
        ('SI302', null, null, 'Programación Orientada a Objetos', null),
        ('FB202', null, null, 'Química II', null),
        ('SI401', null, null, 'Lenguaje de Programación', null),
        ('EE615', null, null, 'Control I', null),
        ('GP101', null, null, 'Introducción a la Ingeniería Industrial', null),
        ('TE401', null, null, 'Termodinámica', null),
        ('SI503', null, null, 'Ingeniería de Procesos', null),
        ('HU201', null, null, 'Sociología', null),
        ('FB303', null, null, 'Calculo Multivariable', null),
        ('FB501', null, null, 'Matemática Aplicada', null),
        ('AFA552', null, null, 'Taller Restauracion De Monumentos', null),
        ('AFA532', null, null, 'Ingles 1', null),
        ('AFA533', null, null, 'Ingles 2', null),
        ('AFA607', null, null, 'Presentacion De Proyectos', null),
        ('AFA606', null, null, 'Teoria Del Color 1', null),
        ('AFA645', null, null, 'Diseño Grafico Por Computadora 1', null),
        ('AFA646', null, null, 'Diseño Grafico Por Computadora 2', null),
        ('AFA407', null, null, 'Estadistica 2', null),
        ('AFA701', null, null, 'Dibujo De Arte', null),
        ('AFA703', null, null, 'Integracion De Las Artes', null),
        ('AFA704', null, null, 'Escultura Y Ceramica', null),
        ('AFA705', null, null, 'Percepcion Sensorial', null),
        ('AFA706', null, null, 'Maquetas Y Aeromodelistica', null),
        ('AFA707', null, null, 'Modelistica', null),
        ('AFA708', null, null, 'Aeromodelistica', null),
        ('AFA709', null, null, 'Diseño Del Mueble', null),
        ('AFA710', null, null, 'Ceramica Experimental', null),
        ('AFA711', null, null, 'Fotografia Y Cine', null),
        ('AFA713', null, null, 'Cine Y Literatura', null),
        ('AFA714', null, null, 'Musica, Teatro Y Danza', null),
        ('AFA715', null, null, 'Telares', null),
        ('AFA716', null, null, 'Arte En Eltiempo', null),
        ('AFA731', null, null, 'Pintura 1', null),
        ('AFA733', null, null, 'Escultura 1', null),
        ('AFA734', null, null, 'Escultura 2', null),
        ('EE211', null, null, 'Maquinas Electricas I', null),
        ('EE603', null, null, 'Sistemas Dinamicos', null),
        ('EE637', null, null, 'Sistemas Digitales Basados En Microprocesadores', null),
        ('ELEC02', null, null, 'Electivo', null),
        ('BMA01', null, null, 'Calculo Diferencial', null),
        ('BRN01', null, null, 'Realidad Nacional, Constitución Y Derechos Humanos', null),
        ('BEG01', null, null, 'Economía General', null),
        ('TP313', null, null, 'Diseño Grafico', null),
        ('GP403', null, null, 'Sistemas Productivos', null),
        ('ST285', null, null, 'Aplicacion De Negocios Electronicos', null),
        ('GP134', null, null, 'Modelos De Gestion Empresarial', null),
        ('ST232', null, null, 'Lenguajes De Programacion Orientado A Objetos', null),
        ('ST231', null, null, 'Taller De Herramientas Software I', null),
        ('GP404', null, null, 'Planeamiento Y Control De La Produc.', null),
        ('TP203', null, null, 'Maquinaria E Instrumentacion Industrial', null),
        ('GP113', null, null, 'Diseno Del Trabajo Ii', null),
        ('GP112', null, null, 'Diseno Del Trabajo I', null),
        ('GP234', null, null, 'Analisis Economico En Ingenieria', null),
        ('ST334', null, null, 'Sistemas De Comunicacion De Datos', null),
        ('GP114', null, null, 'Diseno Y Disposicion De Planta', null),
        ('GP575', null, null, 'Diagnostico Empresarial', null),
        ('ST124', null, null, 'Simulacion', null),
        ('ST123', null, null, 'Investigacion De Operaciones Ii', null),
        ('TP324', null, null, 'Ergonomia', null),
        ('GP555', null, null, 'Gestion De Negocios I', null),
        ('BQU01', null, null, 'Quimica I', null),
        ('EE319', null, null, 'Eficiencia Energetica Y Energias Renovables', null),
        ('HU200', null, null, 'Idiomas (mínimo nivel intermedio)', null),
        ('HU300', null, null, 'Actividades extracurriculares (3 tipos diferentes)', null),
        ('HU400', null, null, 'Prácticas pre profesionales  (mínimo 6 meses)', null),
        ('GP702', null, null, 'Ingenieria Economica', null),
        ('SI130', null, null, 'Gestion de la Información', null),
        ('GE130', null, null, 'Gestion de Negocios y Estrategia Empresarial', null),
        ('SI180', null, null, 'Modelo Paramétrico de Datos', null),
        ('GP133', null, null, 'Desarrollo Organizacional', null),
        ('ST253', null, null, 'Tecnicas De Documentacion Y Archivos', null),
        ('TP304', null, null, 'Diseno En Ingenieria', null),
        ('TP303', null, null, 'Ingenieria De Materiales', null),
        ('GP244', null, null, 'Sistemas De Costos', null),
        ('GP233', null, null, 'Contabilidad De Costos Y Presup.', null),
        ('EE320', null, null, 'Circuitos Electricos I', null),
        ('BMA05', null, null, 'Estadistica Y Probabilidades', null),
        ('SI101', null, null, 'Introducción al Pensamiento y a la Ing. de Sistemas', null),
        ('SI505', null, null, 'Diseño de Base de Datos', null),
        ('SI807', null, null, 'Sistemas de Inteligencia de Negocio', null),
        ('SI806', null, null, 'Desarrollo Adaptativo e Integrado del SW', null),
        ('SI085', null, null, 'Aplicación de Negocios Electrónicos.', null),
        ('SI801', null, null, 'Modelo del Sistema Viable', null),
        ('CB211', null, null, 'Quimica Basica', null),
        ('CB112', null, null, 'Matemática Discreta', null),
        ('FB301', null, null, 'Matemática Discreta', null),
        ('TE802', null, null, 'Ingeniería del Producto', null),
        ('TE801', null, null, 'Automatización y Control de Procesos', null),
        ('CB302', null, null, 'Física I', null),
        ('ST111', null, null, 'Teoría de Sistemas', null),
        ('ST221', null, null, 'Algoritmo y Estructura de Datos', null),
        ('CB121', null, null, 'Cálculo Diferencial', null),
        ('HU301', null, null, 'Metodología de la Investigación', null),
        ('FB101', null, null, 'Geometría Analítica', null),
        ('FB403', null, null, 'Ecuaciones Diferenciales', null),
        ('SI405', null, null, 'Modelado Conceptual de Datos', null),
        ('FB405', null, null, 'Estadística Aplicada', null),
        ('SI204', null, null, 'Teoría General de Sistemas', null),
        ('SI705', null, null, 'Estándares de la Ing. de Sistemas', null),
        ('SI704', null, null, 'Gestión de la Ingeniería de Sistemas', null),
        ('GE603', null, null, 'Ingeniería del Trabajo II', null),
        ('GE602', null, null, 'Contabilidad Financiera', null),
        ('GP155', null, null, 'Gerencia de Recursos Humanos', null),
        ('BMA07', null, null, 'Algoritmos Y Estructuras De Datos', null),
        ('GP254', null, null, 'Economía de la Tecnología', null),
        ('GE112', null, null, 'Teoria de Juegos y la Negociación', null),
        ('SI118', null, null, 'Teoria de la Complejidad', null),
        ('BIE01', null, null, 'Idioma Extranjero O Lengua Nativa En El Nivel Intermedio', null),
        ('EE384', null, null, 'Ingenieria Economica', null),
        ('EE353', null, null, 'Analisis De Sistemas De Potencia I', null),
        ('EE214', null, null, 'Maquinas Electricas Ii', null),
        ('EE345', null, null, 'Instalaciones Electricas I', null),
        ('EE705', null, null, 'Gestion Y Liderazgo', null),
        ('EE706', null, null, 'Innovacion Y Emprendimiento', null),
        ('EE354', null, null, 'Analisis De Sistemas De Potencia Ii', null),
        ('EE225', null, null, 'Maquinas Electricas Iii', null),
        ('EE346', null, null, 'Instalaciones Electricas Ii', null),
        ('EE811', null, null, 'Electronica De Potencia', null),
        ('EE805', null, null, 'Topicos De Ingenieria', null),
        ('EE806', null, null, 'Formulacion Y Gestion De Proyectos', null),
        ('EE445', null, null, 'Proyecto De Fin De Carrera', null),
        ('EE315', null, null, 'Centrales Electricas I', null),
        ('ELEC03', null, null, 'Electivo', null),
        ('EE446', null, null, 'Proyecto De Tesis', null),
        ('ELEC04', null, null, 'Electivo', null),
        ('ELEC05', null, null, 'Electivo', null),
        ('ELEC06', null, null, 'Electivo', null),
        ('EE375', null, null, 'Estabilidad De Sistemas De Potencia', null),
        ('EE376', null, null, 'Proteccion De Sistemas De Potencia', null),
        ('EE377', null, null, 'Operacion Y Control De Sistemas De Potencia', null),
        ('EE335', null, null, 'Alta Tension I', null),
        ('GP223', null, null, 'Contabilidad Financiera', null),
        ('TP224', null, null, 'Procesos Industriales Ii', null),
        ('TP223', null, null, 'Procesos Industriales I', null),
        ('ST274', null, null, 'Base De Datos', null),
        ('ST114', null, null, 'Teoria De Decisiones', null),
        ('BMT01', null, null, 'Metodologia Del Trabajo Universitario', null),
        ('ST324', null, null, 'Sistemas Operativos', null),
        ('TP505', null, null, 'Gestion Y Aseguramiento De Calidad Total', null),
        ('EE150', null, null, 'Introduccion A La Ingenieria Del Computador', null),
        ('GP102', null, null, 'Organizacion Y Metodos', null),
        ('ST113', null, null, 'Investigacion De Operaciones I', null),
        ('GP154', null, null, 'Administracion De Recursos Humanos', null),
        ('GP545', null, null, 'Proyecto De Tesis En Ing. Industrial Ii', null),
        ('ST215', null, null, 'Seguridad Informatica', null),
        ('CB101', null, null, 'Geometría Analitica', null),
        ('SI707', null, null, 'Ingeniería de Software', null),
        ('SI301', null, null, 'Teoría y Ciencia de Sistemas Aplicados', null),
        ('SI095', null, null, 'Ingeniería Empresarial', null),
        ('SI207', null, null, 'Sistemas Biológicos y Ecológicos', null),
        ('SI205', null, null, 'Algoritmia y Estructura de datos', null),
        ('FB111', null, null, 'Física Moderna', null),
        ('HU112', null, null, 'Comportamiento Organizacional', null),
        ('CB201', null, null, 'Quimica General-', null),
        ('ST101', null, null, 'Introduccion A La Ingenieria De Sistemas-', null),
        ('TP301', null, null, 'Dibujo De Ingenieria-', null),
        ('ST103', null, null, 'Teoria General De Sistemas-', null),
        ('ST202', null, null, 'Lenguajes De Programacion Estructurado-', null),
        ('CB122', null, null, 'Calculo Numerico-', null),
        ('CB412', null, null, 'Estadistica Aplicada-', null),
        ('HS301', null, null, 'Idiomas I', null),
        ('GP334', null, null, 'Bolsa de Valores y Mercado Bursátil', null),
        ('HS404', null, null, 'Realidad Nacional e Internacional', null),
        ('ST224', null, null, 'Auditoría de Sistemas', null),
        ('ST234', null, null, 'Comercio Electrónico', null),
        ('ST264', null, null, 'Administración de Tecnologías de la Información', null),
        ('ST425', null, null, 'Introducción a la Robótica', null),
        ('ST133', null, null, 'Dinamica De Sistemas', null),
        ('ST344', null, null, 'Sistemas Humanos', null),
        ('TP503', null, null, 'Control Estadistico De Procesos', null),
        ('GP515', null, null, 'Planeamiento Y Direccion Estrategica', null),
        ('ST236', null, null, 'Proyecto De Tesis En Ing. Sistemas Ii', null),
        ('ST235', null, null, 'Proyecto De Tesis En Ing. Sistemas I', null),
        ('TP265', null, null, 'Robotica', null),
        ('SI116', null, null, 'Gestion de la Configuracion de Sistemas de Informacion', null),
        ('SI122', null, null, 'Cibernetica y Teoría de Control', null),
        ('SI135', null, null, 'Intercambio Electrónico de Datos e Interoperabilidad', null),
        ('SI126', null, null, 'Verificacion y Validacion de Sistemas', null),
        ('SI140', null, null, 'Gestión del Conocimiento', null),
        ('SI077', null, null, 'Inteligencia Artificial', null),
        ('SI105', null, null, 'Diseño de Portales y Desarrollo Web', null),
        ('SI107', null, null, 'Semiótica', null),
        ('SI109', null, null, 'Gestión del Ciclo de Vida en el Desarrollo del Software', null),
        ('SI117', null, null, 'Ingeniería de Sistemas', null),
        ('SI119', null, null, 'Taller de Diseño de Sistemas Inteligentes', null),
        ('SI150', null, null, 'Analítica de Datos', null),
        ('SI155', null, null, 'Ciberseguridad', null),
        ('SI127', null, null, 'Diseño Gráfico e Iconográfico', null),
        ('SI111', null, null, 'Teoría De Decisiones', null),
        ('SI114', null, null, 'Base De Datos', null),
        ('BMA03', null, null, 'Algebra Lineal', null),
        ('AFA432', null, null, 'Cálculo Diferencial E Integral', null),
        ('BMA04', null, null, 'Cálculo Avanzado I', null),
        ('SI115', null, null, 'Gestión de Comunidades y Redes Sociales', null),
        ('GE114', null, null, 'Teoría de Precios', null),
        ('GE116', null, null, 'Gestión de Proyectos', null),
        ('GE115', null, null, 'Desarrollo Económico', null),
        ('HU115', null, null, 'Realidad Internacional', null),
        ('GE117', null, null, 'Juegos de Negocio', null),
        ('GE113', null, null, 'Taller de Consultoría de Empresas', null),
        ('SI120', null, null, 'Gestión de las Tecnologias de la Información', null),
        ('TE123', null, null, 'Industria y Medio Ambiente', null),
        ('TE122', null, null, 'Procesos AgroIndustriales', null),
        ('TE126', null, null, 'Gestión del Mantenimiento', null),
        ('GE128', null, null, 'Diagnóstico de Empresas', null),
        ('SI112', null, null, 'Analítica del Negocio', null),
        ('TE111', null, null, 'Innovación y Gestión Tecnológica', null),
        ('TE803', null, null, 'SISTEMAS INTEGRADOS DE CALIDAD', null),
        ('GE906', null, null, 'GESTION FINANCIERA', null),
        ('ST155', null, null, 'CIBERSEGURIDAD', 'ST155');