insert into organization_unit_type (id, name)
values  (1, 'Universidad'),
        (2, 'Facultad'),
        (3, 'Especialidad');

insert into organization_unit (id, code, name, organization_unit_type_id, parent_organization_id)
values  (35, 'N', 'Facultad de Ciencias', 2, 1),
        (34, 'C', 'Facultad de Ingeniería Civil', 2, 1),
        (33, 'M', 'Facultad de Ingeniería Mecanica', 2, 1),
        (32, 'S', 'Facultad de Ingeniería Ambiental', 2, 1),
        (39, 'P', 'Facultad de Ingeniería de Petróleo y Gas Natural', 2, 1),
        (38, 'L', 'Facultad de Ingeniería Electrica y Electronica', 2, 1),
        (37, 'A', 'Facultad de Arquitectura, Urbanismo y Artes', 2, 1),
        (36, 'Q', 'Facultad de Ingeniería Quimica y Textil', 2, 1),
        (41, 'G', 'Facultad de Ingeniería Geológica, Minera y Metalúrgica', 2, 1),
        (40, 'E', 'Facultad de Ingeniería Económica, Estadística y Ciencias Sociales', 2, 1),
        (31, 'I', 'Facultad de Ingeniería Industrial y de Sistemas', 2, 1),
        (115, 'M5', 'Ingeniería Naval', 3, 33),
        (114, 'M4', 'Ingeniería Mecánica Y Eléctrica', 3, 33),
        (113, 'M3', 'Ingeniería Mecánica', 3, 33),
        (112, 'L3', 'Ingeniería De Telecomunicaciones', 3, 38),
        (119, 'N3', 'Química', 3, 35),
        (118, 'N2', 'Matemáticas', 3, 35),
        (117, 'N1', 'Física', 3, 35),
        (116, 'M6', 'Ingeniería Mecatrónica', 3, 33),
        (11, 'I1', 'Ingenieria Industrial', 3, 31),
        (12, 'I2', 'Ingenieria de Sistemas', 3, 31),
        (13, 'S3', 'Ingeniería Ambiental', 3, 32),
        (15, 'E1', 'Ingeniería Económica', 3, 40),
        (14, 'C1', 'Ingeniería Civil', 3, 34),
        (125, 'Q2', 'Ingeniería Textil', 3, 36),
        (19, 'G3', 'Ingeniería De Minas ', 3, 41),
        (18, 'G2', 'Ingeniería Metalúrgica', 3, 41),
        (17, 'G1', 'Ingeniería Geológica', 3, 41),
        (16, 'E3', 'Ingeniería Estadística', 3, 40),
        (123, 'P3', 'Ingeniería De Petróleo Y Gas Natural', 3, 39),
        (128, 'A1', 'Arquitectura', 3, 37),
        (111, 'L2', 'Ingeniería Electrónica', 3, 38),
        (110, 'L1', 'Ingeniería Eléctrica', 3, 38),
        (122, 'P2', 'Ingeniería Petroquímica', 3, 39),
        (121, 'N6', 'Ciencia De La Computación', 3, 35),
        (120, 'N5', 'Ingeniería Física', 3, 35),
        (127, 'S2', 'Ingeniería De Higiene Y Seguridad Industrial', 3, 32),
        (126, 'S1', 'Ingeniería Sanitaria', 3, 32),
        (124, 'Q1', 'Ingeniería Química', 3, 36),
        (1, 'UNI', 'Universidad Nacional de Ingeniería', 1, null),
        (2, 'I3', 'Ingeniería de Software', 3, 31);