name: CI Pull Request

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  pull_request:
    branches: [main, next, develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
