name: CI Pipeline

on:
  workflow_call:   
  
env:
  SPRING_DATASOURCE_DATABASE: mydb
  SPRING_DATASOURCE_HOST: localhost
  SPRING_DATASOURCE_PORT: 5432
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: password
  
jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    env:
      THREAD_API_URL: test
      SPRING_ALLOWED_ORIGINS: http://localhost:3000
      SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/mydb" 
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.SPRING_DATASOURCE_DATABASE }}
          POSTGRES_USER: ${{ env.SPRING_DATASOURCE_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.SPRING_DATASOURCE_PASSWORD }}
        ports:
          - "5432:5432"

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        
      - name: Make Gradlew executable
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test

      - name: Prepare the application
        run: ./gradlew assemble
